"""initial schema

Revision ID: 92402c314542
Revises: 
Create Date: 2026-10-02 11:20:55.686805

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92402c314542'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('principal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schools_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('jenjang_type', sa.Enum('TK', 'SD', 'SMP', 'SMA', 'University', name='jenjangtype', native_enum=False, length=32), nullable=False),
    sa.Column('kurikulum_version', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'jenjang_type', name='uq_tenant_name_jenjang')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_auth_ref', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('principal', 'teacher', 'student', 'parent', 'admin', 'super_admin', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('audience', sa.Enum('all', 'class', 'jenjang', name='announcementaudience', native_enum=False, length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('bypassed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('jurusan', sa.String(length=128), nullable=True),
    sa.Column('wali_kelas_id', sa.Integer(), nullable=True),
    sa.Column('academic_year', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['wali_kelas_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_school_id'), ['school_id'], unique=False)

    op.create_table('message_threads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('participant_ids', sa.JSON(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_threads_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_threads_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('applicable_grade_levels', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['message_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_thread_id'), ['thread_id'], unique=False)

    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=16), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'day_of_week', 'period_number', name='uq_schedule_class_day_period')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('nis', sa.String(length=64), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('enrollment_status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_nis'), ['nis'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_user_id'), ['user_id'], unique=True)

    op.create_table('attendances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('hadir', 'izin', 'sakit', 'alpa', name='attendancestatus', native_enum=False, length=16), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', name='uq_attendance_student_date')
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendances_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_student_id'), ['student_id'], unique=False)

    op.create_table('grades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=32), nullable=False),
    sa.Column('category', sa.Enum('formatif', 'sumatif', 'PR', 'tugas', name='gradecategory', native_enum=False, length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_grade_score_range'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grades_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grades_subject_id'), ['subject_id'], unique=False)

    op.create_table('report_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='reportcardstatus', native_enum=False, length=16), nullable=False),
    sa.Column('kurikulum_version', sa.String(length=64), nullable=False),
    sa.Column('compiled_data', sa.JSON(), nullable=True),
    sa.Column('finalized_by', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finalized_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_cards_student_id'), ['student_id'], unique=False)

    op.create_table('spp_bills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('unpaid', 'paid', 'overdue', name='sppbillstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spp_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spp_bills_student_id'), ['student_id'], unique=False)

    op.create_table('spp_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('receipt_no', sa.String(length=64), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['spp_bills.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_no')
    )
    with op.batch_alter_table('spp_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spp_payments_bill_id'), ['bill_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spp_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spp_payments_bill_id'))

    op.drop_table('spp_payments')
    with op.batch_alter_table('spp_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spp_bills_student_id'))

    op.drop_table('spp_bills')
    with op.batch_alter_table('report_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_cards_student_id'))

    op.drop_table('report_cards')
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grades_subject_id'))
        batch_op.drop_index(batch_op.f('ix_grades_student_id'))

    op.drop_table('grades')
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendances_student_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_date'))
        batch_op.drop_index(batch_op.f('ix_attendances_class_id'))

    op.drop_table('attendances')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_user_id'))
        batch_op.drop_index(batch_op.f('ix_students_school_id'))
        batch_op.drop_index(batch_op.f('ix_students_nis'))
        batch_op.drop_index(batch_op.f('ix_students_class_id'))

    op.drop_table('students')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_schedules_subject_id'))
        batch_op.drop_index(batch_op.f('ix_schedules_class_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_thread_id'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))

    op.drop_table('messages')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_tenant_id'))

    op.drop_table('subjects')
    with op.batch_alter_table('message_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_threads_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_message_threads_school_id'))

    op.drop_table('message_threads')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_school_id'))

    op.drop_table('classes')
    op.drop_table('audit_logs')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_announcements_school_id'))

    op.drop_table('announcements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_school_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('tenants')
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_tenant_id'))

    op.drop_table('schools')
    # ### end Alembic commands ###
